sample_schedule:
  name: Daily Report
  schedule_type: cron
  expression: 0 0 * * *
  enabled: true
  last_run: null
  next_run: '2025-04-27T00:00:00+05:30'
  created_at: '2025-04-26T18:59:31+05:30'
  updated_at: '2025-04-26T18:59:31+05:30'
  report_request:
    input_file: null
    reference_file: null
    output_format: csv
    rule_set_id: null
